// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwfefplvruawsbspwpxh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3ZmVmcGx2cnVhd3Nic3B3cHhoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNDYzMjgsImV4cCI6MjA2NDcyMjMyOH0.q2g4YZeUpmOOmK2LO7KKb-B8ZTpsoxJ9b1H_Wf11_LM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);